name: JPNReader
options:
  bundleIdPrefix: com.joegraham
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  SwiftyTesseract:
    url: https://github.com/SwiftyTesseract/SwiftyTesseract.git
    from: "4.0.1"

targets:
  JPNReader:
    type: application
    platform: macOS
    sources:
      - JPNReader
    settings:
      base:
        INFOPLIST_FILE: JPNReader/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: JPNReader/Resources/JPNReader.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.joegraham.JPNReader
        PRODUCT_NAME: JPNReader
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
    dependencies:
      - package: SwiftyTesseract

schemes:
  JPNReader:
    build:
      targets:
        JPNReader: all
    run:
      config: Debug
